Repository melix/astro4j, pull requests merged in 2025-01, with the labels that each got.

#471 Update SpectroHeliograph.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/SpectroHeliograph.java
Labels: in: jsolex

#470 Update dependency io.micronaut.platform:micronaut-platform to v4.7.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#474 Fix scripting module
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Dedistort.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Loader.java
  jsolex-scripting/build.gradle.kts
  jsolex-scripting/src/main/resources/META-INF/native-image/astro4j/jsolex-scripting/reflect-config.json
  jsolex/src/main/resources/whats-new.md
  jsolex/src/main/resources/whats-new_FR.md
Labels: bug

#472 Update dependency ch.qos.logback:logback-classic to v1.5.16
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#475 Add ability to process SER files in standalone script runner
  build-logic/src/main/kotlin/me.champeau.astro4j.base.gradle.kts
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParamsIO.java
  jsolex-scripting/build.gradle.kts
  jsolex-scripting/src/main/java/me/champeau/a4j/jsolex/cli/LoggingListener.java
  jsolex-scripting/src/main/java/me/champeau/a4j/jsolex/cli/ScriptLoggingListener.java
  jsolex-scripting/src/main/java/me/champeau/a4j/jsolex/cli/ScriptingEntryPoint.java
  jsolex-scripting/src/main/resources/META-INF/native-image/astro4j/jsolex-scripting/jni-config.json
  jsolex-scripting/src/main/resources/META-INF/native-image/astro4j/jsolex-scripting/reflect-config.json
  jsolex/src/main/resources/whats-new.md
  jsolex/src/main/resources/whats-new_FR.md
Labels: enhancement

#473 Update dependency com.diffplug.spotless:spotless-plugin-gradle to v7
  build-logic/build.gradle.kts
Labels: type: dependency-upgrade

#481 Update dependency org.apache.groovy:groovy to v4.0.25
  build-logic/src/main/kotlin/me.champeau.astro4j.base.gradle.kts
Labels: type: dependency-upgrade

#482 Annotate active regions
  docs/src/docs/asciidoc/en/jsolex.adoc
  docs/src/docs/asciidoc/fr/jsolex.adoc
  gradle/libs.versions.toml
  jsolex-core/build.gradle.kts
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/expr/BuiltinFunction.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Crop.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/ImageDraw.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Rotate.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Scaling.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/RequestedImages.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/ActiveRegion.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/ActiveRegions.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/PhenomenaDetector.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/PhenomenaListener.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/GeneratedImageKind.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/FitsUtils.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/MetadataSupport.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/NOAAActiveRegion.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/NOAARegions.java
  jsolex-core/src/main/java/module-info.java
  jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties
  jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties
  jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageSelector.java
  jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java
  jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/image-selection.fxml
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/image-selection.properties
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/image-selection_fr_FR.properties
  jsolex/src/main/resources/whats-new.md
  jsolex/src/main/resources/whats-new_FR.md
Labels: in: jsolex

#469 Update dependency gradle to v8.12.1
  gradle/wrapper/gradle-wrapper.properties
Labels: type: dependency-upgrade

#483 Add parallactic angle correction
  .github/workflows/gradle.yml
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ObservationDetails.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ObservationDetailsSerializer.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParamsIO.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/Setup.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/SolarParametersUtils.java
  jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties
  jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties
  jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ExposureCalculator.java
  jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ProcessParamsController.java
  jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SetupEditor.java
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.fxml
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.properties
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params_fr_FR.properties
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/setup-editor.fxml
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/setup-editor.properties
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/setup-editor_fr_FR.properties
  jsolex/src/main/resources/whats-new.md
  jsolex/src/main/resources/whats-new_FR.md
Labels: enhancement, in: jsolex

#484 Update dependency com.google.code.gson:gson to v2.12.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#485 Fix unclosed file descriptors
  jserfile/src/main/java/me/champeau/a4j/ser/SerFileReader.java
  jsolex-scripting/build.gradle.kts
  jsolex/src/main/resources/whats-new.md
  jsolex/src/main/resources/whats-new_FR.md
Labels: bug, in: jserfile

#487 Add button to delete SER file after processing
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/CaptureSoftwareMetadataHelper.java
  jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.fxml
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.properties
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app_fr_FR.properties
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties
  jsolex/src/main/resources/whats-new.md
  jsolex/src/main/resources/whats-new_FR.md
Labels: enhancement, in: jsolex

#488 Add columns to the batch view
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/event/ProcessingDoneEvent.java
  jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java
  jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java
  jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/BatchItem.java
  jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties
  jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties
Labels: in: jsolex

#486 Update plugin me.champeau.jmh to v0.7.3
  math/build.gradle.kts
Labels: type: dependency-upgrade
